sudo: required
language: ganeric
services:
    - docker
before install:
    - docker build -t danarus/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true danarus/docker-react npm run test
deploy:
    provider: 
    region:
    app:
    env:
    bucket_name:
    bucket_path:
    on:
        branch: master 