language: ganeric
sudo: required
services:
    - docker
before install:
    - docker build -t danarus/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true danarus/docker-react npm run test 
# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: us-east-2
#     app: docker-reacte
#     env: DockerReacte-env
#     bucket_name: elasticbeanstalk-us-east-2-136102615569
#     bucket_path: docker-reacte
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#         secure: $AWS_SECRET_KEY