sudo: required
language: genric
services:
    - docker
before install:
    - docker build -t danarus/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true danarus/docker-react npm run test